version: "1"
secrets:
- name: AWS_ACCESS_KEY_ID
  key: Adityad92/simple-nodejs-app/AWS_ACCESS_KEY_ID
  engine: native
  type: repo
- name: AWS_SECRET_ACCESS_KEY
  key: Adityad92/simple-nodejs-app/AWS_SECRET_ACCESS_KEY
  engine: native
  type: repo
- name: S3_BUCKET
  key: Adityad92/simple-nodejs-app/S3_BUCKET
  engine: native
  type: repo

steps:
  - name: sample bash plugin
    image: adicop49/vela-sample:bash
    pull: always
    parameters:
      url: https://wynk.in/manifest.json
      method: GET

  - name: plugin-to-upload-s3
    image: adicop49/vela-s3-upload-plugin:1-final
    pull: always
    secrets:
    - source: AWS_ACCESS_KEY_ID
      target: AWS_ACCESS_KEY_ID
    - source: AWS_SECRET_ACCESS_KEY
      target: AWS_SECRET_ACCESS_KEY
    - source: S3_BUCKET
      target: S3_BUCKET
    commands: env
    parameters:
      AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: "us-east-1"
      S3_BUCKET: S3_BUCKET


  # - name: install
  #   image: node:latest
  #   ruleset:
  #     if:
  #       branch: [master]
  #       event: [pull_request, push, tag]
  #   commands:
  #     - node install

  # - name: lint
  #   image: node:latest
  #   commands:
  #     - node test

  # - name: build
  #   image: node:latest
  #   pull: always
  #   commands:
  #     - node build